### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by quetzalsly** [xivapi/ffxiv-datamining#16]
Hey just wondering if this will this be updated for 5.01 and 5.05 when it comes out? a lot of people on discord using the data to study the game. Thanks.

**Comment by IrealiTY** [comment]
Commit: 1339b08

5.01 Updated.
We'll make sure 5.05 will be there in a timely manner.

**Comment by quetzalsly** [comment]
Thanks for the update! Was just wondering why PlaceName.csv, ContentFinderCondition.csv have not changed? they should contain the four new eden raids right?

**Comment by IrealiTY** [comment]
Afaik the names and places were already in the 5.0 Build

**Comment by ArcaneDisgea** [comment]
They weren't inside, maybe old saint build or something, I just pushed the 5.01 fix with latest saint and did the thing all should be good now.
